### ISSUE TITLE
Reentry Typo LM Academy

### ISSUE THREAD

**Issue by impact4279** [ReentryGame/ReentryBugsAndWiki#106]
# Typo

## Which program did you find a flaw in?
Apollo, specifically LM

## Which section
Lunar Module Academy

## Where did you find it
Lesson 5 - Lunar Guidance Computer

## What's the wrong word or phrase?
"displayd"

## What should it be?
"displayed"

![ReEntry 24 11 2020 19_37_26 (2)](https://user-images.githubusercontent.com/74985268/100137470-cf1cc380-2e8c-11eb-825b-8d7309cec8f7.png)

**Comment by sundhaug92** [comment]
Fixed by https://github.com/ReentryGame/DefaultMissions/commit/405400b2dd2ed80e79684325ad3ec9ed90bee78b
