### ISSUE TITLE
Reentry Typo LM Academy

### ISSUE THREAD

**Issue by impact4279** [ReentryGame/ReentryBugsAndWiki#107]
# Typo

## Which program did you find a flaw in?
Apollo, LM
![ReEntry 24 11 2020 21_26_19 (2)](https://user-images.githubusercontent.com/74985268/100147574-d7c8c600-2e9b-11eb-96f9-89eeea98919f.png)

## Which section
Academy

## Where did you find it
Lesson 6 - Flight modes

## What's the wrong word or phrase?
"presice"

## What should it be?
"precise"

**Comment by sundhaug92** [comment]
2m from issue posted to fix committed, not bad eh?
