### ISSUE TITLE
Apollo Boost Prep Checklist T-15min typo’s

### ISSUE THREAD

**Issue by SamuelSamouris** [ReentryGame/ReentryBugsAndWiki#114]
# Typo

## Which program did you find a flaw in?
```Apollo``` 
## Which section
```Checklist```
## Where did you find it
```Boost Prep```
## What's the wrong word or phrase?
```lv Thrust (2) - OFF & l+-/PC IND sw - I+-```
## What should it be?
Idk

**Comment by sundhaug92** [comment]
cubey found this
![image](https://user-images.githubusercontent.com/519283/108623585-070db580-7440-11eb-83ed-ca72939c64dd.png)

**Comment by sundhaug92** [comment]
I think this is one of the mojibake bugs that should be fixed in 0.75

**Comment by sundhaug92** [comment]
@SamuelSamouris confirm for closure?
