### ISSUE TITLE
Typo in Mercury Checklist

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#117]
# Typo

## Which program did you find a flaw in?
```Mercury``` 
## Which section
```Academy```
## Where did you find it
```Checklist - Emergency Procedures - Orbit - point 2.e```
## What's the wrong word or phrase?
```"e. of Fire the retros manually"```
## What should it be?
```"e. or Fire the retros manually"```

**Comment by sundhaug92** [comment]
ty, I'll make sure Petri pull the fix in for 0.75
