### ISSUE TITLE
Wrong key in Academy Text

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#118]
# Typo

## Which program did you find a flaw in?
```Mercury``` 
## Which section
```Academy```
## Where did you find it
```In some of the Mercury Academies, but cannot recall which one (sorry). But I found it in the resource.assets file, line 273368```
## What's the wrong word or phrase?
```"(use T to turn on a Flashlight)"```
## What should it be?
```"(use F to turn on a Flashlight)"```

**Comment by sundhaug92** [comment]
Yeah I think that's the old default-binding, one moment
