### ISSUE TITLE
MA-6 Historic Mission Description Typo

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#120]
# Typo

## Which program did you find a flaw in?
```Mercury``` 
## Which section
```Missions```
## Where did you find it
```Mercury Historic Missions - MA-6```
## What's the wrong word or phrase?
```"It will use the new and powerfull ..."```
## What should it be?
```"It will use the new and powerful ..."```

**Comment by sundhaug92** [comment]
Sorry for taking so long ;)

**Comment by testunde** [comment]
> Sorry for taking so long ;)

This fix took ages. 😁
