### ISSUE TITLE
Mercury Campaign Radio Chatter typo

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#124]
# Typo

## Which program did you find a flaw in?
```Mercury```
## Which section
```Campaigns```
## Where did you find it
```Campaign 1: Orbital Survival: Mission 1 - Interior Inspection: Radio Chatter dialogue```
## What's the wrong word or phrase?
```"CC: This if FLIGHT, ..."```
## What should it be?
```"CC: This is FLIGHT, ..."```

**Comment by petriw** [comment]
Fixed.
