### ISSUE TITLE
Mercury Campaign Radio Chatter typo at T-20

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#125]
# Typo

## Which program did you find a flaw in?
```Mercury```
## Which section
```Campaigns```
## Where did you find it
```Campaign 1: Orbital Survival: Mission 2: Radio Chatter dialogue```
## What's the wrong word or phrase?
```"CC: Ge are still go for launch."```
## What should it be?
```"CC: We are still go for launch."```

**Comment by sundhaug92** [comment]
Not seeing this typo, guessing I'm missing a file in the 0.72 branch, so I'll fix it in the 0.75 branch

**Comment by petriw** [comment]
Fixed.
