### ISSUE TITLE
Campaign 1 - Mission 3 Description typo

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#126]
# Typo

## Which program did you find a flaw in?
```Mercury``` 
## Which section
```Campaigns```
## Where did you find it
```Campaign 1: Orbital Survival - Mission 3: Atlas```
## What's the wrong word or phrase?
```"Being far more powerful than the Atlas, it is capable..."```
## What should it be?
```"Being far more powerful than the Redstone, it is capable..."```

**Comment by sundhaug92** [comment]
Strange, can't find that text. @petriw?

**Comment by testunde** [comment]
Its Mission 3, pardon me

**Comment by sundhaug92** [comment]
Yeah I just can't find the string `Being far more powerful than the`

**Comment by testunde** [comment]
I know why, in the description it says `then`, not `than`

**Comment by petriw** [comment]
Fixed.
