### ISSUE TITLE
Campaign 1 Text typo

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#127]
# Typo

## Which program did you find a flaw in?
```Mercury``` 
## Which section
```Campaigns```
## Where did you find it
```Campaign 1, between the "Long Haul" and "Hawaii" mission buttons.```
## What's the wrong word or phrase?
```"This is caused a bif of a setback, but..."```
## What should it be?
```"This is caused a bit of a setback, but..."```

**Comment by petriw** [comment]
Fixed.
