### ISSUE TITLE
Campaign 1 - Mission 5 Description typo

### ISSUE THREAD

**Issue by testunde** [ReentryGame/ReentryBugsAndWiki#128]
# Typo

## Which program did you find a flaw in?
```Mercury``` 
## Which section
```Campaigns```
## Where did you find it
```Campaign 1: Orbital Survival - Mission 5: Hawaii```
## What's the wrong word or phrase?
```"..., and currently in the 24th orbits, it's time..."```
## What should it be?
```"..., and currently in the 24th orbit, it's time..."```

**Comment by petriw** [comment]
Fixed.
