### ISSUE TITLE
Reentry Typo

### ISSUE THREAD

**Issue by PhotonSP** [ReentryGame/ReentryBugsAndWiki#133]
# Typo

## Which program did you find a flaw in?
Apollo
## Which section
Campaign III
## Where did you find it
Thrust of the Engineers
## What's the wrong word or phrase?
"The crew is ready to go hom."
## What should it be?
"The crew is ready to go home."

**Comment by sundhaug92** [comment]
Looks like this was fixed in https://github.com/ReentryGame/DefaultMissions/commit/7d9e490463aa8a73f38510db81ed5834670a3ac1
