### ISSUE TITLE
Found some typos I believe

### ISSUE THREAD

**Issue by Fox-2-Flyer** [ReentryGame/ReentryBugsAndWiki#137]
# Typo

## Which program did you find a flaw in?
Mercury, Gemini,
## Which section
Mercury: Friendship 7 mission, Gemini: Quickstart Campaign
## What's the wrong word or phrase?
Mercury: "yon" Gemini: "l low"
## What should it be?
Mercury: "you" Gemini: "low

**Comment by sundhaug92** [comment]
PRs fixing this:
ReentryGame/DefaultMissions#21
ReentryGame/DefaultMissions#22
