### ISSUE TITLE
Mercury-Atlas 6 - Reward is not given after mission completion

### ISSUE THREAD

**Issue by sundhaug92** [ReentryGame/ReentryBugsAndWiki#17]
From excel/discord
Version: 
Mission: Mercury -> Historic -> Mercury-Atlas 6
Originally reported by: 
Once landed Reward is not given after mission completion

**Comment by sundhaug92** [comment]
@hmelo25 Could you be more specific on the GPU? Nvidia or AMD?

**Comment by hmelo25** [comment]
Of Course:
Windows 10 Ultimate 64 bit OS.16 GB memory RamProcessor: Intel(R) Core 17-4790 CPU @ 3.60 HzVideo Card: Nvidia Geforce GTX 760 2 GB GPU





    On Saturday, January 5, 2019, 12:31:20 PM AST, Martin Sundhaug <notifications@github.com> wrote:  
 
 
@hmelo25 Could you be more specific on the GPU? Nvidia or AMD?

**Comment by sundhaug92** [comment]
@hmelo25 Thanks. Presuming you mean Windows 10 Pro (since Ultimate isn't a thing in Windows 10 and Windows 7 Ultimate was upgraded to 10 Pro)
