### ISSUE TITLE
Decompress & Repress Handles Mercury craft

### ISSUE THREAD

**Issue by TheFlyingFishx** [ReentryGame/ReentryBugsAndWiki#30]
When the Decompressing used in same time with Repress,both of them loses their sound and an error-like sounds activates.
![20190107130616_1](https://user-images.githubusercontent.com/46443943/50765107-90bc9200-127d-11e9-9716-288392ddffaf.jpg)

**Comment by sundhaug92** [comment]
Can confirm. No exceptions in logfile.

**Comment by sundhaug92** [comment]
Fixed in 0.212.EA
