### ISSUE TITLE
Mercury Academy Lesson 2 Typo Welcome back message

### ISSUE THREAD

**Issue by Vosene** [ReentryGame/ReentryBugsAndWiki#44]
# Typo

## Which program did you find a flaw in?
Mercury
## Which section
Academy
## Where did you find it
Lesson 2 - Launch & Ascent
## What's the wrong word or phrase?
"Welcome back, xxx. In this tutorial we will go through all the steps required to launch, and try to complete an ascent. This is the FINAL CHECKs checklist in your mission pad, press [M] to acces it."
## What should it be?
"Welcome back, xxx. In this tutorial, we will go through all the steps required to complete a launch and try to complete an ascent. This is the FINAL CHECKS checklist in your mission pad, press [M] to access it."

**Comment by sundhaug92** [comment]
Updated OP so it fits the template

**Comment by Vosene** [comment]
Corrected text should say … and try to complete AN ascent.

**Comment by sundhaug92** [comment]
Updated OP according to their comment and grammarly proposal
