### ISSUE TITLE
Mercury Checklist Typo, Flashlight hotkey

### ISSUE THREAD

**Issue by jasonims** [ReentryGame/ReentryBugsAndWiki#45]
# Typo

Which program did you find a flaw in?
Mercury

## Which section
Checklists

## Where did you find it
Pre-Dark Checklist 

## What's the wrong word or phrase?
Step 1 states that flashlight is [T]

## What should it be?
Should be [F]

**Comment by jasonims** [comment]
found this error in another acadamy instructions for electrical.

**Comment by sundhaug92** [comment]
@jasonims Which one?

**Comment by jasonims** [comment]
Not sure, but it was one of the radio communications at the bottom of the screen I believe.  I'll rerun it later... but it wasn't a checklist this time.

**Comment by nashsclay** [comment]
Found on the Mercury - Lesson 4 Electricity
It states
`CC: When you are on the STANDBY batteries, you need to conserver power. This is done by shutting down systems you don't need like the blood check, ASCS, the lights (use T to turn on a Flashlight) etc.` As op posted, should be letter F

**Comment by sundhaug92** [comment]
@nashsclay Could you post as separate issue?
