### ISSUE TITLE
Typo in Gemini Agena rendezvous mission

### ISSUE THREAD

**Issue by abdullah-radwan** [ReentryGame/ReentryBugsAndWiki#60]
# Typo

## Which program did you find a flaw in?
Gemini
## Which section
Missions
## Where did you find it
Agena rendezvous early access mission.
## What's the wrong word or phrase?
CC: We are 1h 20m 21s from the initial transfer burn. Ensure you are in SEF attitude, 'burn will be in retrograde direction'.
## What should it be?
The burn will be in prograde direction.

**Comment by sundhaug92** [comment]
Looks like this is fixed by now
