### ISSUE TITLE
Typo in Gemini Agena rendezvous mission #2

### ISSUE THREAD

**Issue by abdullah-radwan** [ReentryGame/ReentryBugsAndWiki#61]
# Typo

## Which program did you find a flaw in?
Gemini
## Which section
Missions
## Where did you find it
Agena rendezvous early access mission.
## What's the wrong word or phrase?
CC: 20 seconds to OAMS burn on 'prograde' direction.
## What should it be?
20 seconds to OAMS burn on retrograde direction.

**Comment by sundhaug92** [comment]
Looks like this has been fixed now
