### ISSUE TITLE
Typo LM academy (lesson 1)

### ISSUE THREAD

**Issue by Raffson** [ReentryGame/ReentryBugsAndWiki#67]
# Typo

## Which program did you find a flaw in?
```Lunar Module``` 
## Which section
```Academy Lesson 1```
## Where did you find it
```The messages in the middle at the bottom```
## What's the wrong word or phrase?
1.```Press the OPEN HATCH to open the hatch```
2.```...two of the batteries has a low power tap...```
3.```...let's turn off the two batteries, and everything inside the cabin will become dark.```
4.```Notice the talkback indicator changed to barberpole, meaning the battery is off line. Set the Decent Battery 2 LO do OFF...```
## What should it be?
1.```Press the OPEN HATCH button to open the hatch```
2.```...two of the batteries have a low power tap...```
3.```...let's turn off the two batteries, extinguishing the flood lights that illuminate the cabin.```
4.```Notice the talkback indicator changed to barberpole, meaning the battery is offline. Set the Decent Battery 2 LO to OFF...```

**Comment by sundhaug92** [comment]
Fixed
