### ISSUE TITLE
Typo LM academy (lesson 2)

### ISSUE THREAD

**Issue by Raffson** [ReentryGame/ReentryBugsAndWiki#68]
# Typo

## Which program did you find a flaw in?
Lunar Module
## Which section
Academy Lesson 2
## Where did you find it
The messages in the middle at the bottom
## What's the wrong word or phrase?
1. ... , so don't worry if you don't understand all of this.
2. ...during the initial part of a mission where the Lunar Module is involved, all of the major systems needs to be powered up before the LM is ready for flight.
3. This is because the Lunar Module batteries No. 1 and 4 is connected to the DC buses by using their low voltage taps.
4. Also, a lot of the instruments on Panel 1 and 2 has a light illuminated above them, indicating that they are not yet set up correctly.
5. ... , we will see that the lights will extuinguish.
6. I recommend using the flashlight as we are powering up the Lunar Module.
7. The Subsystems Activation checklist consists of 4 checklists, part I to part IV.
8. Select SUBSYSTEM ACTIVATION.
9. Do not yet press anything, ...
10. We have two panels where all of the available circuit breakers are available, namely Panel 11 and Panel 16.
11. The checklist starts with Panel 11, so do this as well.
12. You can either select to use the checklist guide system, or perform the checklist manually.
13. Do this by either pressing REQUEST from the Checklist, step 3, or by setting the switch yourself.
14. The last thing we wish to do...
15. ... , but if this is the first time you go through this, I recommend using the checklist guide to go through this part. I will explain some of the systems are you progress, so pay attention to these messages too.
16. First of all, some of the circuit breakers are closed to power some instrumentation and gauged used to monitor the EPS, etc.
17. ... , you can see that most batteries are off line, ...
18. ... , the 4 batteries in the decent stage are on line, ...
19. Next, set up the Primary Glycol Loop by following the checklist section. Start doing this now and press ROGER.
20. The next part of the checklist is where we get all the major systems connected to the EPS we set up.
21. Next, set up the primary subliminator to get the glycol moving among the systems.
22. Please note that some lights are at maximum setting while the hatch is open.
23. Complete this now, and press ROGER when complete.
24. Part II and Part III involved the ECS system and the COMM systems.
25. These two systems are very early in development and are disabled in this version.
26. Part IV contains the last few sections used to activate the LM subsystems, and is where we test the ascent batteries, pressurize the RCS systems and deploy the landing gears.
27. The ascent batteries are mandatory for a normal ascent from the Lunar Surface and back to the CM, and is what will power the electricity during the ascent.
28. These are all about checking the pressure and temp of the substances for the ascent and descent stage. Press ROGER when these to sections are complete.
29. Run the checklist now, and press ROGER when ready, (AMS He part)
30. The be able to use the RCS system, ...
31. The final section is the deploymen of the Landing Gear. The landing gears are the four legs attached to the decent section.
## What should it be?
1. ... , so don't worry if you don't understand all of them. (because we're referring to "the parts")
2. ...during the initial part of **the** mission ~~where the Lunar Module is involved~~, all of the major systems **need** to be powered up before the LM is ready for flight.
3. This is because the Lunar Module batteries No. 1 and 4 **are** connected to the DC **busses** by using their low voltage taps.
4. Also, a lot of the instruments on Panel 1 and 2 **have** a light illuminated above them, indicating that they are not yet set up correctly.
5. ... , we will see that the lights will **extinguish**.
6. I recommend using the flashlight **while** powering up the Lunar Module.
7. The Subsystems Activation checklist consists of 4 parts. (this is more concise)
8. Select SUBSYSTEM ACTIVATION **I**. (assuming you want us to select the first part)
9. Do not press anything **yet**, ...
10. We have two panels **with** all ~~of the~~ available circuit breakers ~~are available~~, namely **Panels** 11 and 16. (again, more concise way of saying the same thing)
11. The checklist **begins** with Panel 11, so let's get started.
12. You can either **choose** to use the checklist guide system, or perform the checklist manually.
13. Do this by either pressing REQUEST **on** the Checklist **in** step 3, or by setting the switch yourself.
14. The last thing we **need** to do... (because it's more of an necessity)
15. ... , but if this is your the first time, I recommend using the checklist guide. I will explain some of the systems **as** you progess, so pay attention to these messages ~~too~~. (more concise)
16. First of all, some of the circuit breakers are closed to power some instrumentation used to monitor the EPS, etc. (gauged ought to be gauges, but gauges are part of instrumentation)
17. ... , you can see that most batteries are **offline**, ...
18. ... , the 4 batteries in the decent stage are **online**, ...
19. Next, set up the Primary Glycol Loop by following the **respective** checklist ~~section~~. Start doing this now and press ROGER **when you're done**.
20. In the next part of the checklist we'll connect all the major systems to the EPS (which we've set up earlier). ("which we've set up earlier" can be left out to make it more concise)
21. Next, set up the primary **sublimator** to get the glycol **flowing through** the systems.
22. Please note that some lights are at maximum **intensity** while the hatch is open. (perhaps change "some lights" to "the flood lights"? or are there other lights i'm missing?)
23. Complete this now, and press ROGER when **done**. (repetition of the word "complete")
24. **Parts** II and III **involve** the ECS and COMM systems. (more concise)
25. These two systems are **still** in development and **thus** disabled in this version.
26. Part IV contains the last few sections used to activate the LM subsystems where we test the ascent batteries, pressurize the RCS, and deploy the landing **gear**.
27. The ascent batteries are mandatory for a normal ascent from the Lunar Surface ~~and~~ back to the CM, ~~and is what will~~ **powering** the ~~electricity~~ **LM** during ~~the~~ ascent.
28. These are all about checking the pressure and **temperature** of the substances for the ascent and descent **stages**. Press ROGER when these **two** sections are complete.
29. Run the checklist now, and press ROGER when ready. (AMS He part, comma used instead of a full stop, aka a point)
30. **To** be able to use the RCS ~~system~~, ... (the S in RCS already stands for system)
31. The final section is the **deployment** of the Landing Gear. The landing **gear consists of** four legs attached to the decent section.

**Comment by Raffson** [comment]
Nr 25 is actually redundant cause it's definitely subject to change, so it can be ignored. I left similar issues out of this report...

**Comment by sundhaug92** [comment]
Fixed
