### ISSUE TITLE
Multiple typos in LM academy lesson 3

### ISSUE THREAD

**Issue by Raffson** [ReentryGame/ReentryBugsAndWiki#69]
# Typo

## Which program did you find a flaw in?
Lunar Module
## Which section
LM academy lesson 3
## Where did you find it
The messages in the middle at the bottom
## What's the wrong word or phrase?
**GENERAL REMARKS: All occurrences of a-c or d-c => use  capital letters AC and DC instead without the dash. Also occurrences of "on line" and "off line" should become "online" and "offline", i.e. without the space. Finally, I notice inconsistencies when referring to Panel X, most of the times Panel is written with capital 'P', but sometimes it's written with a small 'p'**
1. During lunar stay, specific combinations of the five descent stage batteries can be paralleled to provide LM power.
2. Primary a-c power is provided by two inverters, which supply 115+- 2.5-volt, 400+- 0.4-cps (synced condition), a-c power to LM subsystems.
3. Panel 11 and Panel 16 contains all the circuit breakers,...
4. The flight manual contains a lot of details on how things are connected. In this lesson, we will focus on the operation of it.
5. First of all, the descent stage batteries No.1 and No.4 has two modes of being connected. Either by their low voltage taps, of high voltage taps.
6. You can see if these batteries are online with their high or low voltage taps based on the talkback indicator related to that bettery. If it shows LO, the low voltagte taps are in use, and GRAY if high voltage is on line.
7. On panel 14, and the descent power section,...
8. To bring the low voltage tap off line as well, disconnecting the entire battery, set the LMP BAT 1 LO-V switch to OFF as well.
9. ... by using the two gauges on the left if Panel 14.
10. The POWER/TEMP MON knob allows you to cycle through each battery, d-c bus and a-c bus.
11. The VOLTs gauge should show 28 volts, and amps should show 0.
12. ..., and are set on line when their switches are set to ON.
13. It can be connected to the CDR d-c bus and the LMP d-c bus.
14. The other batteries are connected to the LMP bus...
15. Bat 5 powerd the LMP bus...
16. This will make this entire side go dark, as the electrical system that connects LMP Bat 1 and 2 to the LMP D-C bus is disconnected from the LMP D-C bus.
17. The VOLTS and AMPS gauge should now show 0, as the LMP D-C bus is completely off. The DC BUS FAULT comp light should be illuminating, indicating that a DC BUS is off line.
18. ..., you can see a two CROSS TIE fuses. These are used to connect the CDR battery electronics to the LMP D-C bus.
19. Close the CROSS TIE BUS fuse to do this. Notice that the power is now back. The CDR electrical system now powers the LMP D-C bus.
20. The VOLTS and AMPS gauge should now indicate that the LMP D-C Bus is back on line again as well.
21. When the CROSS TIE fuses are opened for both circuits, the CDR D-C and the LMP D-C bus are completly isolated from eachother.
22. Verify that this swich is set to INV 2. This is the normal position.
23. The Subsystems Activation checklist disconnects the INV 1 from the circuit. Set the INV switch to INV 1, and notice that the integral lights goes out. These lights require A-C power, and it means that our A-C power is out.
24. The reason for this is that the INV 1 fuse is open, so the inverter is not getting D-C power from the CDR D-C bus. Close the INV 1 fuse on Panel 11 (CDR side). This should bring INV 1 on line.
25. When in OFF/ED,...
26. ..., and that the entire descent stage electrical system is de-powered.
27. If you now take a look around inside the cockpit,...
28. ..., and de-power the power line going from the CSM to the LM...
29. Use the flash light to connect the ASCENT BAT 5 on line.
30. Then set the ASCENT BAT 6 on line. The CDR and LMP bus is once again...
31. Please also note that the EPS: DISP fuse on Panel 16 needs to be closed for the VOLTS and the AMPS gauge on P14 to work.
32. I know there was a lot,...
## What should it be?
**GENERAL REMARKS: All occurrences of a-c or d-c => use  capital letters AC and DC instead without the dash. Also occurrences of "on line" and "off line" should become "online" and "offline", i.e. without the space. Finally, I notice inconsistencies when referring to Panel X, most of the times Panel is written with capital 'P', but sometimes it's written with a small 'p'**
1. During lunar stay, specific combinations of the five descent stage batteries can be paralleled to provide **power to the LM**.
2. Primary **AC** power is provided by two inverters, which supply 115+- 2.5 volt**s and** 400+- 0.4 **Hz** (synced condition) to **the** LM**'s** subsystems.
3. **Panels 11 and 16 contain** all the circuit breakers,...
4. The flight manual contains a lot of details on how the EPS is wired to other systems, though in this lesson we'll only learn how to operate it. (assuming 'things' refers to the EPS)
5. First of all, the descent stage batteries No.1 and No.4 have two connection modes, either connected to the low voltage taps, or to the high voltage taps.
6. You can see if these batteries are online with their high or low voltage taps based on their respective talkback indicators. If it shows LO, the low **voltage** taps are in use, and GRAY when using the high voltage taps.
7. On the DESCENT POWER section of Panel 14,... (making "descent power" capitalized will probably make it clear it's a panel name, though it's not necessary so change at your own discretion)
8. To bring the low voltage tap **offline** --as well--, disconnecting the --entire-- battery entirely, set the LMP BAT 1 LO-V switch to OFF --as well--.
9. ... by using the two gauges on the left **of** Panel 14.
10. The POWER/TEMP MON knob allows you to cycle through each battery, AC and DC buses. (yeah i know, i mentioned it ought to be 'busses' in lesson 2 but it turns out this changed, both British and American English use 'buses' now, will open a new issue to refine lesson 2)
11. The **VOLTS** gauge should show 28 volts, and **AMPS** should show 0. (earlier, and also later, these gauges got referenced with its name in capital letters)
12. ..., and **get online** when their switches are set to ON.
13. It can be connected to **both the CDR's and/or LMP's DC bus(es)**. (more concise)
14. The **lunar battery is** connected to the LMP bus... (or is this a bug? cause i only get the LMP/CDR flag on the LUNAR BAT)
15. Bat 5 **powers** the LMP bus...
16. This will make the LMP's side go dark, as the electrical system that connects LMP Bat 1 and 2 to the LMP DC bus is disconnected. (i also notice panel lights turn off on CDR's side, only the CW lights, timers, AGC and small lights on panels 1, 2 & 3 are still on, also the left flood light won't go out, also the flood lights of the left console stay on, even after disconnecting the entire EPS and with a closed hatch, not sure if I'm missing something.. :s)
17. The VOLTS and AMPS gauge should now **read** 0 since we opened the BAT FEED TIE circuit breakers, effectively disconnecting the LMP DC bus. The DC BUS light should also be illuminated on the CW (Caution & Warning) panel, indicating that a DC BUS is offline. (btw, i missed another  "should now show 0" earlier, although "read" would technically be more correct, it's not that much of an issue)
18. ..., you can see --a-- two CROSS TIE fuses. These are used to connect the CDR and LMP DC buses. (cause we connect both DC buses together)
19. Close the CROSS TIE BUS fuse and notice it restores power given that the CDR's BAT FEED TIE fuses are closed. The CDR's DC bus now provides power to the LMP's DC bus. (although the CDR's BAT FEED TIE fuses still don't work, i assume this is what's needed)
20. The VOLTS and AMPS gauge should now indicate that the LMP DC bus is back online --again as well--. (more concise and I noticed bus was written with a capital letter while this wasn't the case earlier, unless I missed another instance)
21. When both CROSS TIE fuses are opened, the CDR's and LMP DC buses are completely isolated from each other. (I might have missed other instances of "eachother", the correct form is "each other")
22. Verify that this switch is set to INV 2 which is the normal position.
23. The Subsystems Activation checklist disconnects --the-- INV 1 from the circuit. Set the INV switch to INV 1, and notice that the integral lights turn off. These lights require AC power, which is currently not provided.
24. This is because the INV 1 fuse is open, so the inverter is not getting power from the CDR's DC bus. Close the INV 1 fuse on Panel 11 (CDR side) which should bring INV 1 online and bring the lights back up.
25. When set to (the) OFF/ED (position),... (leave "the" and "position" out if you want to be more concise)
26. ..., and that the entire electrical system of the descent stage is cut off.
27. If you --now-- take a look around inside the cockpit,...
28. ..., and cut the power --line-- going (from the CSM to the LM) /(through the umbilical)... (not sure what's best here, so choose between "from the CSM to the LM" and "through the umbilical", or perhaps use both putting 1 of the 2 between parenthesis)
29. Use the **flashlight and** connect --the-- **NORMAL** ASCENT BAT 5 --on line--.
30. Then connect the NORMAL ASCENT BAT 6 and notice that the CDR and LMP buses are once again...
31. Please also note that the EPS: DISP fuse on Panel 16 needs to be closed for the VOLTS and AMPS gauges on Panel 14 to work. (P14 -> Panel 14, for consistency)
32. I know we covered a lot of things,...

**Comment by sundhaug92** [comment]
Could you split this up a bit? 32 issues in one is a bit hard to fit on a screen
