### ISSUE TITLE
Multiple typos in LM academy lesson 2

### ISSUE THREAD

**Issue by Raffson** [ReentryGame/ReentryBugsAndWiki#70]
# Typo

## Which program did you find a flaw in?
Lunar Module
## Which section
Academy lesson 2
## Where did you find it
Messages at the bottom in the middle
## What's the wrong word or phrase?
**GENERAL REMARK: I made a mistake correcting 'buses' to 'busses', this turns out to be false**
1. ..., and use the guidance logic to step through the major parts of it.
2. ..., and the tunnel between the LM and the CM is open.
3. ..., but skim through the checklist to get familiar with the major parts of it,...
4. he checklist begins with Panel 11,...
5. The last thing we need to do in this section is to open the descent H2O valve.
6. The EPS checklist will take you through some tests as well,...
7. The be able to use the RCS,...
8. The next checklist is all about testing parts of the RCS system,...
9. The landing gear consists of four legs attached to the decent section.
## What should it be?.
**GENERAL REMARK: I made a mistake correcting 'buses' to 'busses', this turns out to be false**
1. ..., and use the guidance logic to step through the major parts --of it--.
2. ..., and the tunnel between the LM and the CM is open. (no typo, but on my end the hatch is still closed...)
3. ..., but skim through the checklist to get familiar with the major parts --of it--,...
4. The checklist begins with Panel 11,...
5. The last thing we need to do in this section is --to-- opening the descent H2O valve.
6. The EPS checklist will take you through some tests --as well--,...
7. To be able to use the RCS,...
8. The next checklist is all about testing parts of the RCS --system--,... (missed this one since I mentioned in the first issue that the S stands for system, which was actually the same sentence as 7, though you missed this one ;) )
9. The landing gear consists of four legs attached to the **descent** section. (made a typo in "decent", ought to be "descent", apologies for that one)

**Comment by sundhaug92** [comment]
0.7 should fix point 7
