### ISSUE TITLE
Typo, Gemini, Tutorial 7

### ISSUE THREAD

**Issue by toad1998** [ReentryGame/ReentryBugsAndWiki#89]
# Typo

## Which program did you find a flaw in?
``Gemini`` 
## Which section
``Academy``
## Where did you find it
``Tutorial 7 - The Sequencer``
## What's the wrong word or phrase?
``1.`` ``works by illuminateing a task``
## What should it be?
``1.`` ``works by illuminating a task``

**Comment by sundhaug92** [comment]
Wow, the bot actually did this one (mostly) right
