### ISSUE TITLE
Typo: mercury Academy, Mission 3

### ISSUE THREAD

**Issue by thedemogamer** [ReentryGame/ReentryBugsAndWiki#94]
# Typo

## Which program did you find a flaw in?
Mercury 
## Which section
Academy
## Where did you find it
Mission 3 - Checklists and Atlas, first dialog. 
## What's the wrong word or phrase?
“Launc Vehicle”
## What should it be?
“Launch Vehicle”

**Comment by sundhaug92** [comment]
Closed as dupe of #79 and #64
