### ISSUE TITLE
Typo, Mercury, Campaign 1 - Mission 5, "imaging"

### ISSUE THREAD

**Issue by toad1998** [ReentryGame/ReentryBugsAndWiki#95]
# Typo
(Found by ``SamSam``)
## Which program did you find a flaw in?
``Mercury``
## Which section
``Campaign 1``
## Where did you find it
``Mission 5 "Hawaii"``
## What's the wrong word or phrase?
``1.`` ``imaging``
## What should it be?
``1.`` ``imagine``

**Comment by sundhaug92** [comment]
Looks like this has been fixed
